### ISSUE TITLE
Fabirisio

### ISSUE THREAD

**Issue by ohkuom** [CasvalDOT/costance#1]

**Comment by CasvalDOT** [comment]
Ciao ahahaha, sono in giro con un amico, se vuoi possiamo sentirci la prossima settimana!! Ho apprezzato molto il guizzo di usare GitHub

**Comment by roccoamico** [comment]
Giovedì?

**Comment by CasvalDOT** [comment]
Ciao vecchio. Ho letto adesso. Sorry. Se vuoi in sto week sono ad Udine al Friuli DOC. Vorrei darti il numero, ma non voglio mettere  il numero qui

**Comment by CasvalDOT** [comment]
@roccoamico dovrei creare una serie di indizi per portarti al mio numero di telefono

**Comment by CasvalDOT** [comment]
@roccoamico scrivimi il numero sulla mia email aziendale. Ti contatto li
